# Generated by Django 6.0.5 on 2026-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('ASSET', '資産'), ('LIABILITY', '負債'), ('EQUITY', '純資産'), ('REVENUE', '収益'), ('EXPENSE', '費用')], max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
